# Generated by Django 2.0.5 on 2018-06-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='カテゴリID')),
                ('category_name', models.TextField(max_length=200, verbose_name='カテゴリ名')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='タグID')),
                ('tag_name', models.TextField(max_length=200, verbose_name='タグ名')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.AddField(
            model_name='categories',
            name='tag_id',
            field=models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together={('tag_id', 'category_id')},
        ),
    ]
