# Generated by Django 2.0.5 on 2018-06-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.TextField(max_length=100, verbose_name='メンバーID')),
                ('member_name', models.TextField(max_length=200, verbose_name='メンバー名称')),
                ('joined_at', models.DateField(verbose_name='入会日')),
                ('insert_at', models.DateField(verbose_name='登録日')),
                ('insert_user', models.IntegerField(verbose_name='登録ユーザ')),
                ('update_at', models.DateField(verbose_name='更新日')),
                ('update_user', models.IntegerField(verbose_name='更新ユーザ')),
            ],
        ),
    ]
