# Generated by Django 2.0.5 on 2018-06-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='insert_at',
            field=models.DateTimeField(verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='members',
            name='joined_at',
            field=models.DateTimeField(verbose_name='入会日時'),
        ),
        migrations.AlterField(
            model_name='members',
            name='update_at',
            field=models.DateTimeField(verbose_name='更新日時'),
        ),
    ]
