# Generated by Django 2.0.5 on 2018-06-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180618_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='insert_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='members',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
