# Generated by Django 2.0.5 on 2018-06-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20180618_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='insert_user',
            field=models.IntegerField(null=True, verbose_name='登録ユーザ'),
        ),
        migrations.AlterField(
            model_name='members',
            name='joined_at',
            field=models.DateTimeField(null=True, verbose_name='入会日時'),
        ),
        migrations.AlterField(
            model_name='members',
            name='update_user',
            field=models.IntegerField(null=True, verbose_name='更新ユーザ'),
        ),
    ]
